/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_void_3_fourchess_AIChess_Coordinate */

#ifndef _Included_cn_void_3_fourchess_AIChess_Coordinate
#define _Included_cn_void_3_fourchess_AIChess_Coordinate
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
